FROM golang:1.22-alpine as builder
RUN apk --update add build-base

WORKDIR /src/app
ADD go.mod .
RUN go mod download

ADD . .
RUN go build -o bin/cronjobs ./cmd/cronjobs

FROM alpine
RUN apk add --no-cache tzdata ca-certificates
WORKDIR /bin/

# Copying binaries
COPY --from=builder /src/app/bin/cronjobs .

RUN chmod +x /bin/cronjobs

# Running the cronjob
CMD /bin/cronjobs;
